name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Compilar com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable

      - name: Disponibilizar o APK pra download
        uses: actions/upload-artifact@v4
        with:
          name: painel-discord-apk
          path: ${{ steps.buildozer.outputs.filename }}
