name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Compilar com a imagem oficial do Buildozer
        run: |
          docker run --rm \
            --volume "$PWD":/home/user/hostcwd \
            kivy/buildozer android debug

      - name: Disponibilizar o APK pra download
        uses: actions/upload-artifact@v4
        with:
          name: painel-discord-apk
          path: bin/*.apk
